apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: liverpool-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          serviceName: liverpool-service
          servicePort: 80