apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liverpool-ingress
  # namespace: {{}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: liverpool-service
            port:
              number: 80
